# Generated by Django 5.2.4 on 2025-07-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_buyerprofile_address_buyerprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
