# Generated by Django 5.2.4 on 2025-07-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_buyerprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='preferences',
        ),
    ]
