# Generated by Django 5.2.4 on 2025-07-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_remove_buyerprofile_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='preferences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
