# Generated by Django 5.2.4 on 2025-07-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_customuser_address_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
